### ISSUE TITLE
mimicFn is not a function

### ISSUE THREAD

**Issue by mariusrak** [wojtekmaj/get-user-locale#114]
I get this error after an update, it's probably because of https://github.com/wojtekmaj/get-user-locale/commit/830255abb4e1bcc092b264520410fff09c46da40
```
TypeError
mimicFn is not a function
Call Stack
 mem
            .../node_modules/mem/dist/index.js:53:12
 undefined
        .../node_modules/get-user-locale/dist/esm/index.js:64:54
```

**Comment by wojtekmaj** [comment]
Do you have a reproducible example? Obviously, can't reproduce that in my environment, tests would have been all red :D
