### ISSUE TITLE
Call could still return null when using fallbackLocale

### ISSUE THREAD

**Issue by bravo-kernel** [wojtekmaj/get-user-locale#80]
Unsure if this is related to this module but I was expecting that defining a `fallbackLocale` would always return a string. I am trying to do this:

```js
import { getUserLocale } from "get-user-locale"

const locale = getUserLocale({
  fallbackLocale: "en",
  useFallbackLocale: true
})

if(["in", "hi-IN"].includes(locale){
  // do something
}
```

However, `include` complains with below type error about possible `null` so I am guessing it is not detected:

```
Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.
```

Any pointers on how to solve this, if possible at all?

**Comment by bravo-kernel** [comment]
It seems I can just add an exclamation mark to `locale` to get rid of the type error. 

```js
if(["in", "hi-IN"].includes(locale!){
  // do something
}
```

Feel free to close unless you think this should be handled by the module.

**Comment by wojtekmaj** [comment]
Unless `useFallbackLocale` was specifically set to `false`, indeed there's no possibility of getting `null` back. I fixed that by adding function overloads :)

**Comment by bravo-kernel** [comment]
Ah, perfect. Much appreciated ❤️
